<option value="ACEH BARAT">ACEH BARAT</option>
<option value="ACEH BARAT DAYA">ACEH BARAT DAYA</option>
<option value="ACEH BESAR">ACEH BESAR</option>
<option value="ACEH JAYA">ACEH JAYA</option>
<option value="ACEH SELATAN">ACEH SELATAN</option>
<option value="ACEH SINGKIL">ACEH SINGKIL</option>
<option value="ACEH TAMIANG">ACEH TAMIANG</option>
<option value="ACEH TENGAH">ACEH TENGAH</option>
<option value="ACEH TENGGARA">ACEH TENGGARA</option>
<option value="ACEH TIMUR">ACEH TIMUR</option>
<option value="ACEH UTARA">ACEH UTARA</option>
<option value="AGAM">AGAM</option>
<option value="ALOR">ALOR</option>
<option value="AMBON">AMBON</option>
<option value="ASAHAN">ASAHAN</option>
<option value="ASMAT">ASMAT</option>
<option value="BADUNG">BADUNG</option>
<option value="BALANGAN">BALANGAN</option>
<option value="BALIKPAPAN">BALIKPAPAN</option>
<option value="BANDA ACEH">BANDA ACEH</option>
<option value="BANDAR LAMPUNG">BANDAR LAMPUNG</option>
<option value="BANDUNG">BANDUNG</option>
<option value="BANDUNG BARAT">BANDUNG BARAT</option>
<option value="BANGGAI">BANGGAI</option>
<option value="BANGGAI KEPULAUAN">BANGGAI KEPULAUAN</option>
<option value="BANGGAI LAUT">BANGGAI LAUT</option>
<option value="BANGKA">BANGKA</option>
<option value="BANGKA BARAT">BANGKA BARAT</option>
<option value="BANGKA SELATAN">BANGKA SELATAN</option>
<option value="BANGKA TENGAH">BANGKA TENGAH</option>
<option value="BANGKALAN">BANGKALAN</option>
<option value="BANGLI">BANGLI</option>
<option value="BANJAR">BANJAR</option>
<option value="BANJARBARU">BANJARBARU</option>
<option value="BANJARMASIN">BANJARMASIN</option>
<option value="BANJARNEGARA">BANJARNEGARA</option>
<option value="BANTAENG">BANTAENG</option>
<option value="BANTUL">BANTUL</option>
<option value="BANYUASIN">BANYUASIN</option>
<option value="BANYUMAS">BANYUMAS</option>
<option value="BANYUWANGI">BANYUWANGI</option>
<option value="BARITO KUALA">BARITO KUALA</option>
<option value="BARITO SELATAN">BARITO SELATAN</option>
<option value="BARITO TIMUR">BARITO TIMUR</option>
<option value="BARITO UTARA">BARITO UTARA</option>
<option value="BARRU">BARRU</option>
<option value="BATAM">BATAM</option>
<option value="BATANG">BATANG</option>
<option value="BATANGHARI">BATANGHARI</option>
<option value="BATU">BATU</option>
<option value="BATU BARA">BATU BARA</option>
<option value="BAU BAU">BAU BAU</option>
<option value="BEKASI">BEKASI</option>
<option value="BELITUNG">BELITUNG</option>
<option value="BELITUNG TIMUR">BELITUNG TIMUR</option>
<option value="BELU">BELU</option>
<option value="BENER MERIAH">BENER MERIAH</option>
<option value="BENGKALIS">BENGKALIS</option>
<option value="BENGKAYANG">BENGKAYANG</option>
<option value="BENGKULU">BENGKULU</option>
<option value="BENGKULU SELATAN">BENGKULU SELATAN</option>
<option value="BENGKULU TENGAH">BENGKULU TENGAH</option>
<option value="BENGKULU UTARA">BENGKULU UTARA</option>
<option value="BERAU">BERAU</option>
<option value="BIAK NUMFOR">BIAK NUMFOR</option>
<option value="BIMA">BIMA</option>
<option value="BINJAI">BINJAI</option>
<option value="BINTAN">BINTAN</option>
<option value="BIREUEN">BIREUEN</option>
<option value="BITUNG">BITUNG</option>
<option value="BLITAR">BLITAR</option>
<option value="BLORA">BLORA</option>
<option value="BOALEMO">BOALEMO</option>
<option value="BOGOR">BOGOR</option>
<option value="BOJONEGORO">BOJONEGORO</option>
<option value="BOLAANG MONGONDOW">BOLAANG MONGONDOW</option>
<option value="BOLAANG MONGONDOW SELATAN">BOLAANG MONGONDOW SELATAN</option>
<option value="BOLAANG MONGONDOW TIMUR">BOLAANG MONGONDOW TIMUR</option>
<option value="BOLAANG MONGONDOW UTARA">BOLAANG MONGONDOW UTARA</option>
<option value="BOMBANA">BOMBANA</option>
<option value="BONDOWOSO">BONDOWOSO</option>
<option value="BONE">BONE</option>
<option value="BONE BOLANGO">BONE BOLANGO</option>
<option value="BONTANG">BONTANG</option>
<option value="BOVEN DIGOEL">BOVEN DIGOEL</option>
<option value="BOYOLALI">BOYOLALI</option>
<option value="BREBES">BREBES</option>
<option value="BUKITTINGGI">BUKITTINGGI</option>
<option value="BULELENG">BULELENG</option>
<option value="BULUKUMBA">BULUKUMBA</option>
<option value="BULUNGAN">BULUNGAN</option>
<option value="BUNGO">BUNGO</option>
<option value="BUOL">BUOL</option>
<option value="BURU">BURU</option>
<option value="BURU SELATAN">BURU SELATAN</option>
<option value="BUTON">BUTON</option>
<option value="BUTON SELATAN">BUTON SELATAN</option>
<option value="BUTON TENGAH">BUTON TENGAH</option>
<option value="BUTON UTARA">BUTON UTARA</option>
<option value="CIAMIS">CIAMIS</option>
<option value="CIANJUR">CIANJUR</option>
<option value="CILACAP">CILACAP</option>
<option value="CILEGON">CILEGON</option>
<option value="CIMAHI">CIMAHI</option>
<option value="CIREBON">CIREBON</option>
<option value="DAIRI">DAIRI</option>
<option value="DEIYAI">DEIYAI</option>
<option value="DELI SERDANG">DELI SERDANG</option>
<option value="DEMAK">DEMAK</option>
<option value="DENPASAR">DENPASAR</option>
<option value="DEPOK">DEPOK</option>
<option value="DHARMASRAYA">DHARMASRAYA</option>
<option value="DOGIYAI">DOGIYAI</option>
<option value="DOMPU">DOMPU</option>
<option value="DONGGALA">DONGGALA</option>
<option value="DUMAI">DUMAI</option>
<option value="EMPAT LAWANG">EMPAT LAWANG</option>
<option value="ENDE">ENDE</option>
<option value="ENREKANG">ENREKANG</option>
<option value="FAK FAK">FAK FAK</option>
<option value="FLORES TIMUR">FLORES TIMUR</option>
<option value="GARUT">GARUT</option>
<option value="GAYO LUES">GAYO LUES</option>
<option value="GIANYAR">GIANYAR</option>
<option value="GORONTALO">GORONTALO</option>
<option value="GORONTALO UTARA">GORONTALO UTARA</option>
<option value="GOWA">GOWA</option>
<option value="GRESIK">GRESIK</option>
<option value="GROBOGAN">GROBOGAN</option>
<option value="GUNUNG KIDUL">GUNUNG KIDUL</option>
<option value="GUNUNG MAS">GUNUNG MAS</option>
<option value="GUNUNGSITOLI">GUNUNGSITOLI</option>
<option value="HALMAHERA BARAT">HALMAHERA BARAT</option>
<option value="HALMAHERA SELATAN">HALMAHERA SELATAN</option>
<option value="HALMAHERA TENGAH">HALMAHERA TENGAH</option>
<option value="HALMAHERA TIMUR">HALMAHERA TIMUR</option>
<option value="HALMAHERA UTARA">HALMAHERA UTARA</option>
<option value="HULU SUNGAI SELATAN">HULU SUNGAI SELATAN</option>
<option value="HULU SUNGAI TENGAH">HULU SUNGAI TENGAH</option>
<option value="HULU SUNGAI UTARA">HULU SUNGAI UTARA</option>
<option value="HUMBANG HASUNDUTAN">HUMBANG HASUNDUTAN</option>
<option value="INDRAGIRI HILIR">INDRAGIRI HILIR</option>
<option value="INDRAGIRI HULU">INDRAGIRI HULU</option>
<option value="INDRAMAYU">INDRAMAYU</option>
<option value="INTAN JAYA">INTAN JAYA</option>
<option value="JAKARTA BARAT">JAKARTA BARAT</option>
<option value="JAKARTA PUSAT">JAKARTA PUSAT</option>
<option value="JAKARTA SELATAN">JAKARTA SELATAN</option>
<option value="JAKARTA TIMUR">JAKARTA TIMUR</option>
<option value="JAKARTA UTARA">JAKARTA UTARA</option>
<option value="JAMBI">JAMBI</option>
<option value="JAYAPURA">JAYAPURA</option>
<option value="JAYAWIJAYA">JAYAWIJAYA</option>
<option value="JEMBER">JEMBER</option>
<option value="JEMBRANA">JEMBRANA</option>
<option value="JENEPONTO">JENEPONTO</option>
<option value="JEPARA">JEPARA</option>
<option value="JOMBANG">JOMBANG</option>
<option value="KAB MALUKU TENGGARA BARAT">KAB MALUKU TENGGARA BARAT</option>
<option value="KAB PEGUNUNGAN BINTANG">KAB PEGUNUNGAN BINTANG</option>
<option value="KAB TIMOR TENGAH SELATAN">KAB TIMOR TENGAH SELATAN</option>
<option value="KAIMANA">KAIMANA</option>
<option value="KAMPAR">KAMPAR</option>
<option value="KAPUAS">KAPUAS</option>
<option value="KAPUAS HULU">KAPUAS HULU</option>
<option value="KARANGANYAR">KARANGANYAR</option>
<option value="KARANGASEM">KARANGASEM</option>
<option value="KARAWANG">KARAWANG</option>
<option value="KARIMUN">KARIMUN</option>
<option value="KARO">KARO</option>
<option value="KATINGAN">KATINGAN</option>
<option value="KAUR">KAUR</option>
<option value="KAYONG UTARA">KAYONG UTARA</option>
<option value="KEBUMEN">KEBUMEN</option>
<option value="KEDIRI">KEDIRI</option>
<option value="KEEROM">KEEROM</option>
<option value="KENDAL">KENDAL</option>
<option value="KENDARI">KENDARI</option>
<option value="KEP. SIAU TAGULANDANG BIARO">KEP. SIAU TAGULANDANG BIARO</option>
<option value="KEPAHIANG">KEPAHIANG</option>
<option value="KEPULAUAN ANAMBAS">KEPULAUAN ANAMBAS</option>
<option value="KEPULAUAN ARU">KEPULAUAN ARU</option>
<option value="KEPULAUAN MENTAWAI">KEPULAUAN MENTAWAI</option>
<option value="KEPULAUAN MERANTI">KEPULAUAN MERANTI</option>
<option value="KEPULAUAN SANGIHE">KEPULAUAN SANGIHE</option>
<option value="KEPULAUAN SELAYAR">KEPULAUAN SELAYAR</option>
<option value="KEPULAUAN SULA">KEPULAUAN SULA</option>
<option value="KEPULAUAN TALAUD">KEPULAUAN TALAUD</option>
<option value="KEPULAUAN YAPEN">KEPULAUAN YAPEN</option>
<option value="KERINCI">KERINCI</option>
<option value="KETAPANG">KETAPANG</option>
<option value="KLATEN">KLATEN</option>
<option value="KLUNGKUNG">KLUNGKUNG</option>
<option value="KOLAKA">KOLAKA</option>
<option value="KOLAKA TIMUR">KOLAKA TIMUR</option>
<option value="KOLAKA UTARA">KOLAKA UTARA</option>
<option value="KONAWE">KONAWE</option>
<option value="KONAWE KEPULAUAN">KONAWE KEPULAUAN</option>
<option value="KONAWE SELATAN">KONAWE SELATAN</option>
<option value="KONAWE UTARA">KONAWE UTARA</option>
<option value="KOTABARU">KOTABARU</option>
<option value="KOTAMOBAGU">KOTAMOBAGU</option>
<option value="KOTAWARINGIN BARAT">KOTAWARINGIN BARAT</option>
<option value="KOTAWARINGIN TIMUR">KOTAWARINGIN TIMUR</option>
<option value="KUANTAN SINGINGI">KUANTAN SINGINGI</option>
<option value="KUBU RAYA">KUBU RAYA</option>
<option value="KUDUS">KUDUS</option>
<option value="KULON PROGO">KULON PROGO</option>
<option value="KUNINGAN">KUNINGAN</option>
<option value="KUPANG">KUPANG</option>
<option value="KUTAI BARAT">KUTAI BARAT</option>
<option value="KUTAI KARTANEGARA">KUTAI KARTANEGARA</option>
<option value="KUTAI TIMUR">KUTAI TIMUR</option>
<option value="LABUHANBATU">LABUHANBATU</option>
<option value="LABUHANBATU SELATAN">LABUHANBATU SELATAN</option>
<option value="LABUHANBATU UTARA">LABUHANBATU UTARA</option>
<option value="LAHAT">LAHAT</option>
<option value="LAMANDAU">LAMANDAU</option>
<option value="LAMONGAN">LAMONGAN</option>
<option value="LAMPUNG BARAT">LAMPUNG BARAT</option>
<option value="LAMPUNG SELATAN">LAMPUNG SELATAN</option>
<option value="LAMPUNG TENGAH">LAMPUNG TENGAH</option>
<option value="LAMPUNG TIMUR">LAMPUNG TIMUR</option>
<option value="LAMPUNG UTARA">LAMPUNG UTARA</option>
<option value="LANDAK">LANDAK</option>
<option value="LANGKAT">LANGKAT</option>
<option value="LANGSA">LANGSA</option>
<option value="LANNY JAYA">LANNY JAYA</option>
<option value="LEBAK">LEBAK</option>
<option value="LEBONG">LEBONG</option>
<option value="LEMBATA">LEMBATA</option>
<option value="LHOKSEUMAWE">LHOKSEUMAWE</option>
<option value="lih Kota">lih Kota</option>
<option value="LIMA PULUH KOTA">LIMA PULUH KOTA</option>
<option value="LINGGA">LINGGA</option>
<option value="LOMBOK BARAT">LOMBOK BARAT</option>
<option value="LOMBOK TENGAH">LOMBOK TENGAH</option>
<option value="LOMBOK TIMUR">LOMBOK TIMUR</option>
<option value="LOMBOK UTARA">LOMBOK UTARA</option>
<option value="LUBUK LINGGAU">LUBUK LINGGAU</option>
<option value="LUMAJANG">LUMAJANG</option>
<option value="LUWU">LUWU</option>
<option value="LUWU TIMUR">LUWU TIMUR</option>
<option value="LUWU UTARA">LUWU UTARA</option>
<option value="MADIUN">MADIUN</option>
<option value="MAGELANG">MAGELANG</option>
<option value="MAGETAN">MAGETAN</option>
<option value="MAHAKAM ULU">MAHAKAM ULU</option>
<option value="MAJALENGKA">MAJALENGKA</option>
<option value="MAJENE">MAJENE</option>
<option value="MAKASSAR">MAKASSAR</option>
<option value="MALAKA">MALAKA</option>
<option value="MALANG">MALANG</option>
<option value="MALINAU">MALINAU</option>
<option value="MALUKU BARAT DAYA">MALUKU BARAT DAYA</option>
<option value="MALUKU TENGAH">MALUKU TENGAH</option>
<option value="MALUKU TENGGARA">MALUKU TENGGARA</option>
<option value="MAMASA">MAMASA</option>
<option value="MAMBERAMO RAYA">MAMBERAMO RAYA</option>
<option value="MAMBERAMO TENGAH">MAMBERAMO TENGAH</option>
<option value="MAMUJU">MAMUJU</option>
<option value="MAMUJU TENGAH">MAMUJU TENGAH</option>
<option value="MAMUJU UTARA">MAMUJU UTARA</option>
<option value="MANADO">MANADO</option>
<option value="MANDAILING NATAL">MANDAILING NATAL</option>
<option value="MANGGARAI">MANGGARAI</option>
<option value="MANGGARAI BARAT">MANGGARAI BARAT</option>
<option value="MANGGARAI TIMUR">MANGGARAI TIMUR</option>
<option value="MANOKWARI">MANOKWARI</option>
<option value="MANOKWARI SELATAN">MANOKWARI SELATAN</option>
<option value="MAPPI">MAPPI</option>
<option value="MAROS">MAROS</option>
<option value="MATARAM">MATARAM</option>
<option value="MAYBRAT">MAYBRAT</option>
<option value="MEDAN">MEDAN</option>
<option value="MELAWI">MELAWI</option>
<option value="MEMPAWAH">MEMPAWAH</option>
<option value="MERANGIN">MERANGIN</option>
<option value="MERAUKE">MERAUKE</option>
<option value="MESUJI">MESUJI</option>
<option value="METRO">METRO</option>
<option value="MIMIKA">MIMIKA</option>
<option value="MINAHASA">MINAHASA</option>
<option value="MINAHASA SELATAN">MINAHASA SELATAN</option>
<option value="MINAHASA TENGGARA">MINAHASA TENGGARA</option>
<option value="MINAHASA UTARA">MINAHASA UTARA</option>
<option value="MOJOKERTO">MOJOKERTO</option>
<option value="MOROWALI">MOROWALI</option>
<option value="MOROWALI UTARA">MOROWALI UTARA</option>
<option value="MUARA ENIM">MUARA ENIM</option>
<option value="MUARO JAMBI">MUARO JAMBI</option>
<option value="MUKO MUKO">MUKO MUKO</option>
<option value="MUNA">MUNA</option>
<option value="MUNA BARAT">MUNA BARAT</option>
<option value="MURUNG RAYA">MURUNG RAYA</option>
<option value="MUSI BANYUASIN">MUSI BANYUASIN</option>
<option value="MUSI RAWAS">MUSI RAWAS</option>
<option value="MUSI RAWAS UTARA">MUSI RAWAS UTARA</option>
<option value="NABIRE">NABIRE</option>
<option value="NAGAN RAYA">NAGAN RAYA</option>
<option value="NAGEKEO">NAGEKEO</option>
<option value="NATUNA">NATUNA</option>
<option value="NDUGA">NDUGA</option>
<option value="NGADA">NGADA</option>
<option value="NGANJUK">NGANJUK</option>
<option value="NGAWI">NGAWI</option>
<option value="NIAS">NIAS</option>
<option value="NIAS BARAT">NIAS BARAT</option>
<option value="NIAS SELATAN">NIAS SELATAN</option>
<option value="NIAS UTARA">NIAS UTARA</option>
<option value="NUNUKAN">NUNUKAN</option>
<option value="OGAN ILIR">OGAN ILIR</option>
<option value="OGAN KOMERING ILIR">OGAN KOMERING ILIR</option>
<option value="OGAN KOMERING ULU">OGAN KOMERING ULU</option>
<option value="OGAN KOMERING ULU SELATAN">OGAN KOMERING ULU SELATAN</option>
<option value="OGAN KOMERING ULU TIMUR">OGAN KOMERING ULU TIMUR</option>
<option value="PACITAN">PACITAN</option>
<option value="PADANG">PADANG</option>
<option value="PADANG LAWAS">PADANG LAWAS</option>
<option value="PADANG LAWAS UTARA">PADANG LAWAS UTARA</option>
<option value="PADANG PANJANG">PADANG PANJANG</option>
<option value="PADANG PARIAMAN">PADANG PARIAMAN</option>
<option value="PADANGSIDIMPUAN">PADANGSIDIMPUAN</option>
<option value="PAGAR ALAM">PAGAR ALAM</option>
<option value="PAHUWATO">PAHUWATO</option>
<option value="PAKPAK BHARAT">PAKPAK BHARAT</option>
<option value="PALANGKARAYA">PALANGKARAYA</option>
<option value="PALEMBANG">PALEMBANG</option>
<option value="PALOPO">PALOPO</option>
<option value="PALU">PALU</option>
<option value="PAMEKASAN">PAMEKASAN</option>
<option value="PANDEGLANG">PANDEGLANG</option>
<option value="PANGANDARAN">PANGANDARAN</option>
<option value="PANGKAJENE KEPULAUAN">PANGKAJENE KEPULAUAN</option>
<option value="PANGKAL PINANG">PANGKAL PINANG</option>
<option value="PANIAI">PANIAI</option>
<option value="PARE PARE">PARE PARE</option>
<option value="PARIAMAN">PARIAMAN</option>
<option value="PARIGI MOUTONG">PARIGI MOUTONG</option>
<option value="PASAMAN">PASAMAN</option>
<option value="PASAMAN BARAT">PASAMAN BARAT</option>
<option value="PASER">PASER</option>
<option value="PASURUAN">PASURUAN</option>
<option value="PATI">PATI</option>
<option value="PAYAKUMBUH">PAYAKUMBUH</option>
<option value="PEGUNUNGAN ARFAK">PEGUNUNGAN ARFAK</option>
<option value="PEKALONGAN">PEKALONGAN</option>
<option value="PEKANBARU">PEKANBARU</option>
<option value="PELALAWAN">PELALAWAN</option>
<option value="PEMALANG">PEMALANG</option>
<option value="PEMATANG SIANTAR">PEMATANG SIANTAR</option>
<option value="PENAJAM PASER UTARA">PENAJAM PASER UTARA</option>
<option value="PENUKAL ABAB LEMATANG ILIR">PENUKAL ABAB LEMATANG ILIR</option>
<option value="PESAWARAN">PESAWARAN</option>
<option value="PESISIR BARAT">PESISIR BARAT</option>
<option value="PESISIR SELATAN">PESISIR SELATAN</option>
<option value="PIDIE">PIDIE</option>
<option value="PIDIE JAYA">PIDIE JAYA</option>
<option value="PINRANG">PINRANG</option>
<option value="POLEWALI MANDAR">POLEWALI MANDAR</option>
<option value="PONOROGO">PONOROGO</option>
<option value="PONTIANAK">PONTIANAK</option>
<option value="POSO">POSO</option>
<option value="PRABUMULIH">PRABUMULIH</option>
<option value="PRINGSEWU">PRINGSEWU</option>
<option value="PROBOLINGGO">PROBOLINGGO</option>
<option value="PULANG PISAU">PULANG PISAU</option>
<option value="PULAU MOROTAI">PULAU MOROTAI</option>
<option value="PULAU TALIABU">PULAU TALIABU</option>
<option value="PUNCAK">PUNCAK</option>
<option value="PUNCAK JAYA">PUNCAK JAYA</option>
<option value="PURBALINGGA">PURBALINGGA</option>
<option value="PURWAKARTA">PURWAKARTA</option>
<option value="PURWOREJO">PURWOREJO</option>
<option value="RAJA AMPAT">RAJA AMPAT</option>
<option value="REJANG LEBONG">REJANG LEBONG</option>
<option value="REMBANG">REMBANG</option>
<option value="ROKAN HILIR">ROKAN HILIR</option>
<option value="ROKAN HULU">ROKAN HULU</option>
<option value="ROTE NDAO">ROTE NDAO</option>
<option value="SABANG">SABANG</option>
<option value="SABU RAIJUA">SABU RAIJUA</option>
<option value="SALATIGA">SALATIGA</option>
<option value="SAMARINDA">SAMARINDA</option>
<option value="SAMBAS">SAMBAS</option>
<option value="SAMOSIR">SAMOSIR</option>
<option value="SAMPANG">SAMPANG</option>
<option value="SANGGAU">SANGGAU</option>
<option value="SARMI">SARMI</option>
<option value="SAROLANGUN">SAROLANGUN</option>
<option value="SAWAHLUNTO">SAWAHLUNTO</option>
<option value="SEKADAU">SEKADAU</option>
<option value="SELUMA">SELUMA</option>
<option value="SEMARANG">SEMARANG</option>
<option value="SERAM BAGIAN BARAT">SERAM BAGIAN BARAT</option>
<option value="SERAM BAGIAN TIMUR">SERAM BAGIAN TIMUR</option>
<option value="SERANG">SERANG</option>
<option value="SERDANG BEDAGAI">SERDANG BEDAGAI</option>
<option value="SERIBU">SERIBU</option>
<option value="SERUYAN">SERUYAN</option>
<option value="SIAK">SIAK</option>
<option value="SIBOLGA">SIBOLGA</option>
<option value="SIDENRENG RAPPANG">SIDENRENG RAPPANG</option>
<option value="SIDOARJO">SIDOARJO</option>
<option value="SIGI">SIGI</option>
<option value="SIJUNJUNG">SIJUNJUNG</option>
<option value="SIKKA">SIKKA</option>
<option value="SIMALUNGUN">SIMALUNGUN</option>
<option value="SIMEULUE">SIMEULUE</option>
<option value="SINGKAWANG">SINGKAWANG</option>
<option value="SINJAI">SINJAI</option>
<option value="SINTANG">SINTANG</option>
<option value="SITUBONDO">SITUBONDO</option>
<option value="SLEMAN">SLEMAN</option>
<option value="SOLOK">SOLOK</option>
<option value="SOLOK SELATAN">SOLOK SELATAN</option>
<option value="SOPPENG">SOPPENG</option>
<option value="SORONG">SORONG</option>
<option value="SORONG SELATAN">SORONG SELATAN</option>
<option value="SRAGEN">SRAGEN</option>
<option value="SUBANG">SUBANG</option>
<option value="SUBULUSSALAM">SUBULUSSALAM</option>
<option value="SUKABUMI">SUKABUMI</option>
<option value="SUKAMARA">SUKAMARA</option>
<option value="SUKOHARJO">SUKOHARJO</option>
<option value="SUMBA BARAT">SUMBA BARAT</option>
<option value="SUMBA BARAT DAYA">SUMBA BARAT DAYA</option>
<option value="SUMBA TENGAH">SUMBA TENGAH</option>
<option value="SUMBA TIMUR">SUMBA TIMUR</option>
<option value="SUMBAWA">SUMBAWA</option>
<option value="SUMBAWA BARAT">SUMBAWA BARAT</option>
<option value="SUMEDANG">SUMEDANG</option>
<option value="SUMENEP">SUMENEP</option>
<option value="SUNGAI PENUH">SUNGAI PENUH</option>
<option value="SUPIORI">SUPIORI</option>
<option value="SURABAYA">SURABAYA</option>
<option value="SURAKARTA">SURAKARTA</option>
<option value="TABALONG">TABALONG</option>
<option value="TABANAN">TABANAN</option>
<option value="TAKALAR">TAKALAR</option>
<option value="TAMBRAUW">TAMBRAUW</option>
<option value="TANA TIDUNG">TANA TIDUNG</option>
<option value="TANA TORAJA">TANA TORAJA</option>
<option value="TANAH BUMBU">TANAH BUMBU</option>
<option value="TANAH DATAR">TANAH DATAR</option>
<option value="TANAH LAUT">TANAH LAUT</option>
<option value="TANGERANG">TANGERANG</option>
<option value="TANGERANG SELATAN">TANGERANG SELATAN</option>
<option value="TANGGAMUS">TANGGAMUS</option>
<option value="TANJUNG BALAI">TANJUNG BALAI</option>
<option value="TANJUNG JABUNG BARAT">TANJUNG JABUNG BARAT</option>
<option value="TANJUNG JABUNG TIMUR">TANJUNG JABUNG TIMUR</option>
<option value="TANJUNG PINANG">TANJUNG PINANG</option>
<option value="TAPANULI SELATAN">TAPANULI SELATAN</option>
<option value="TAPANULI TENGAH">TAPANULI TENGAH</option>
<option value="TAPANULI UTARA">TAPANULI UTARA</option>
<option value="TAPIN">TAPIN</option>
<option value="TARAKAN">TARAKAN</option>
<option value="TASIKMALAYA">TASIKMALAYA</option>
<option value="TEBING TINGGI">TEBING TINGGI</option>
<option value="TEBO">TEBO</option>
<option value="TEGAL">TEGAL</option>
<option value="TELUK BINTUNI">TELUK BINTUNI</option>
<option value="TELUK WONDAMA">TELUK WONDAMA</option>
<option value="TEMANGGUNG">TEMANGGUNG</option>
<option value="TERNATE">TERNATE</option>
<option value="TIDORE KEPULAUAN">TIDORE KEPULAUAN</option>
<option value="TIMOR TENGAH UTARA">TIMOR TENGAH UTARA</option>
<option value="TOBA SAMOSIR">TOBA SAMOSIR</option>
<option value="TOJO UNA UNA">TOJO UNA UNA</option>
<option value="TOLI TOLI">TOLI TOLI</option>
<option value="TOLIKARA">TOLIKARA</option>
<option value="TOMOHON">TOMOHON</option>
<option value="TORAJA UTARA">TORAJA UTARA</option>
<option value="TRENGGALEK">TRENGGALEK</option>
<option value="TUAL">TUAL</option>
<option value="TUBAN">TUBAN</option>
<option value="TULANG BAWANG">TULANG BAWANG</option>
<option value="TULANG BAWANG BARAT">TULANG BAWANG BARAT</option>
<option value="TULUNGAGUNG">TULUNGAGUNG</option>
<option value="WAJO">WAJO</option>
<option value="WAKATOBI">WAKATOBI</option>
<option value="WAROPEN">WAROPEN</option>
<option value="WAY KANAN">WAY KANAN</option>
<option value="WONOGIRI">WONOGIRI</option>
<option value="WONOSOBO">WONOSOBO</option>
<option value="YAHUKIMO">YAHUKIMO</option>
<option value="YALIMO">YALIMO</option>
<option value="YOGYAKARTA">YOGYAKARTA</option>